## Statsbomb API

In [1]:
import numpy as np
from statsbombpy import sb

COMPETITION_ID = 9
SEASON_ID = 27

sb.competitions().head()

c:\Users\Alexander Lorenz\anaconda3\envs\aifc\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [2]:
matches = sb.matches(competition_id=COMPETITION_ID, season_id=SEASON_ID)
matches.head()

c:\Users\Alexander Lorenz\anaconda3\envs\aifc\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3890561,2016-05-14,15:30:00.000,Germany - 1. Bundesliga,2015/2016,Hoffenheim,Schalke 04,1,4,available,...,None,34,Regular Season,PreZero Arena,Felix Brych,Julian Nagelsmann,André Breitenreiter,1.1.0,2,2
1,3890505,2016-04-02,15:30:00.000,Germany - 1. Bundesliga,2015/2016,Bayern Munich,Eintracht Frankfurt,1,0,available,...,None,28,Regular Season,Allianz Arena,Florian Meyer,Josep Guardiola i Sala,Niko Kovač,1.1.0,2,2
2,3890511,2016-04-08,20:30:00.000,Germany - 1. Bundesliga,2015/2016,Hertha Berlin,Hannover 96,2,2,available,...,None,29,Regular Season,Olympiastadion Berlin,Benjamin Brand,Pál Dárdai,Daniel Stendel,1.1.0,2,2
3,3890515,2016-04-09,15:30:00.000,Germany - 1. Bundesliga,2015/2016,Hamburger SV,Darmstadt 98,1,2,available,...,None,29,Regular Season,Volksparkstadion,Peter Sippel,Bruno Labbadia,Dirk Schuster,1.1.0,2,2
4,3890411,2015-12-20,16:30:00.000,Germany - 1. Bundesliga,2015/2016,Hertha Berlin,FSV Mainz 05,2,0,available,...,None,17,Regular Season,Olympiastadion Berlin,Peter Sippel,Pál Dárdai,Martin Schmidt,1.1.0,2,2

In [9]:
events = sb.events(match_id=3895302)
events.columns

Index(['50_50', 'bad_behaviour_card', 'ball_receipt_outcome',
       'ball_recovery_recovery_failure', 'block_deflection',
       'block_save_block', 'carry_end_location', 'clearance_aerial_won',
       'clearance_body_part', 'clearance_head', 'clearance_left_foot',
       'clearance_right_foot', 'counterpress', 'dribble_nutmeg',
       'dribble_outcome', 'duel_outcome', 'duel_type', 'duration',
       'foul_committed_advantage', 'foul_committed_card',
       'foul_committed_penalty', 'foul_won_advantage', 'foul_won_defensive',
       'foul_won_penalty', 'goalkeeper_body_part', 'goalkeeper_end_location',
       'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_technique',
       'goalkeeper_type', 'id', 'index', 'injury_stoppage_in_chain',
       'interception_outcome', 'location', 'match_id', 'minute', 'off_camera',
       'out', 'pass_aerial_won', 'pass_angle', 'pass_assisted_shot_id',
       'pass_body_part', 'pass_cross', 'pass_cut_back', 'pass_deflected',
       'pass_end_location', 'pass_goal_assist', 'pass_height',
       'pass_inswinging', 'pass_length', 'pass_outcome', 'pass_outswinging',
       'pass_recipient', 'pass_recipient_id', 'pass_shot_assist',
       'pass_switch', 'pass_technique', 'pass_through_ball', 'pass_type',
       'period', 'play_pattern', 'player', 'player_id', 'position',
       'possession', 'possession_team', 'possession_team_id', 'related_events',
       'second', 'shot_aerial_won', 'shot_body_part', 'shot_end_location',
       'shot_first_time', 'shot_freeze_frame', 'shot_key_pass_id',
       'shot_one_on_one', 'shot_outcome', 'shot_statsbomb_xg',
       'shot_technique', 'shot_type', 'substitution_outcome',
       'substitution_outcome_id', 'substitution_replacement',
       'substitution_replacement_id', 'tactics', 'team', 'team_id',
       'timestamp', 'type', 'under_pressure'],
      dtype='object')

In [10]:
events

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_save_block,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 3421, 'lineup': [{'player': {'id...",Bayer Leverkusen,904,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Werder Bremen,176,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Werder Bremen,176,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:00:00.000,Half Start,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4218,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Werder Bremen,176,00:01:04.682,Bad Behaviour,NaN
4219,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:01:05.939,Bad Behaviour,NaN
4220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 3421, 'lineup': [{'player': {'id...",Bayer Leverkusen,904,00:23:47.066,Tactical Shift,NaN
4221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 352, 'lineup': [{'player': {'id'...",Werder Bremen,176,00:31:46.845,Tactical Shift,NaN
4222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Bayer Leverkusen,904,00:24:04.669,Shield,NaN

In [4]:
events = events[["timestamp","player","location","type","shot_outcome"]]
mask = events["shot_outcome"].notna()
events[mask].head()

,timestamp,player,location,type,shot_outcome
4093,00:06:48.773,Leonardo Bittencourt,"[100.4, 35.1]",Shot,Blocked
4094,00:07:40.953,Piero Martín Hincapié Reyna,"[114.6, 33.5]",Shot,Saved
4095,00:11:08.471,Julián Malatini,"[106.2, 55.8]",Shot,Blocked
4096,00:13:16.073,Jonathan Tah,"[113.9, 47.4]",Shot,Blocked
4097,00:16:00.956,Granit Xhaka,"[89.2, 42.5]",Shot,Blocked

In [19]:
sb.events(match_id=3895302, split=True, flatten_attrs=False)["shots"]

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,position,location,duration,related_events,shot,match_id,possession_team_id,team_id,player_id,under_pressure
0,c577e730-b9f5-44f2-9257-9e7730c23d7b,436,1,00:06:48.773,6,48,Shot,13,Werder Bremen,From Free Kick,...,Right Center Midfield,"[100.4, 35.1]",0.052872,"[17577869-9441-4463-9633-eaf59865be31, bd9ad18...","{'statsbomb_xg': 0.056644168, 'end_location': ...",3895302,176,176,8826,NaN
1,bbc2c68d-c096-483d-abf4-32c0175a0f55,480,1,00:07:40.953,7,40,Shot,14,Bayer Leverkusen,Regular Play,...,Left Wing Back,"[114.6, 33.5]",0.217872,"[735d168e-bdc9-4ffa-a979-ae74e3046b7e, 7ccfdcc...","{'statsbomb_xg': 0.14338115, 'end_location': [...",3895302,904,904,38004,True
2,12b5206b-9ed0-4b1e-9ec3-f2028187e09f,597,1,00:11:08.471,11,8,Shot,22,Werder Bremen,From Free Kick,...,Right Center Back,"[106.2, 55.8]",0.445768,"[1d6476f0-2ffa-44d9-ae5f-13e4e31a89e8, 5d02d6e...","{'statsbomb_xg': 0.038188405, 'end_location': ...",3895302,176,176,51769,NaN
3,b2c3d59d-3bef-4f8a-ad86-26b69940c64e,684,1,00:13:16.073,13,16,Shot,26,Bayer Leverkusen,From Corner,...,Center Back,"[113.9, 47.4]",0.085298,"[c9983c31-83ff-4aa2-be8b-eae4ef407930, d072b71...","{'statsbomb_xg': 0.052781336, 'end_location': ...",3895302,904,904,8221,NaN
4,bb53b537-1685-4019-9e8f-98f3805828eb,848,1,00:16:00.956,16,0,Shot,33,Bayer Leverkusen,Regular Play,...,Right Defensive Midfield,"[89.2, 42.5]",0.402989,"[5f2e14bd-1aa6-4393-9d43-ddd4aaa39fcb, 93b6fd7...","{'statsbomb_xg': 0.021271583, 'end_location': ...",3895302,904,904,3500,True
5,0247fb51-7bf7-4be6-82d7-bf63892bdd53,854,1,00:16:31.596,16,31,Shot,34,Bayer Leverkusen,From Corner,...,Center Back,"[110.2, 32.6]",1.732516,"[3d252275-eda7-4760-b50f-274d6cd49883, 96147df...","{'statsbomb_xg': 0.029664174, 'end_location': ...",3895302,904,904,8221,True
6,b6b96d19-97e3-4770-996a-f20696123abe,990,1,00:18:28.225,18,28,Shot,38,Werder Bremen,Regular Play,...,Right Center Forward,"[105.4, 45.1]",0.209113,"[1ce33358-4918-4f13-8fcf-252a64bfd659, 82a4343...","{'statsbomb_xg': 0.082292914, 'end_location': ...",3895302,176,176,34870,True
7,cf7357c9-3bd6-425f-ac34-ef7f11897394,1193,1,00:24:27.217,24,27,Shot,42,Bayer Leverkusen,Other,...,Center Forward,"[108.0, 40.0]",0.479048,[fa651b41-5dec-4bc0-aab2-11fca1d29721],"{'statsbomb_xg': 0.7835, 'end_location': [120....",3895302,904,904,32289,NaN
8,93d22a32-8221-4cab-9d68-d68f4b600599,1310,1,00:27:46.504,27,46,Shot,45,Bayer Leverkusen,From Corner,...,Right Defensive Midfield,"[101.5, 47.5]",0.005026,"[3df3ba88-db68-48f7-accb-ff141c1a5ad3, f9aeec7...","{'statsbomb_xg': 0.05010965, 'end_location': [...",3895302,904,904,3500,NaN
9,5d2bf27b-dd07-4895-8744-1673b235fcec,1316,1,00:28:21.806,28,21,Shot,46,Bayer Leverkusen,From Corner,...,Center Back,"[116.3, 46.0]",0.506597,"[10d39b53-a148-4cbb-b1cd-90bb5c65bf2f, 2007b52...","{'statsbomb_xg': 0.10991712, 'end_location': [...",3895302,904,904,8221,True
10,7350b239-c1ab-44b2-9c25-0387553bd338,1319,1,00:28:23.060,28,23,Shot,46,Bayer Leverkusen,From Corner,...,Center Forward,"[116.3, 43.3]",0.025776,[f500afdf-958e-41b7-9011-bacb83a3050b],"{'statsbomb_xg': 0.323069, 'end_location': [11...",3895302,904,904,32289,NaN
11,be78c5ab-d396-4c44-8253-d48373ead6b3,1521,1,00:34:51.122,34,51,Shot,55,Bayer Leverkusen,From Free Kick,...,Right Attacking Midfield,"[109.4, 44.9]",0.191931,"[06511549-2b8e-44fd-8b88-5400399783db, 125bbc7...","{'statsbomb_xg': 0.09542403, 'end_location': [...",3895302,904,904,8804,NaN
12,8cf6ed6f-59f8-455f-8930-f5b71f06c180,1696,1,00:37:40.441,37,40,Shot,58,Bayer Leverkusen,Regular Play,...,Left Attacking Midfield,"[113.1, 27.5]",0.395410,"[2e8aac02-4e72-4c91-9cf9-9dad79e88749, 401facb...","{'statsbomb_xg': 0.07415738, 'end_location': [...",3895302,904,904,33401,True
13,68ccb2b1-d605-4f46-a725-de0ab09acb96,2009,1,00:43:36.743,43,36,Shot,65,Bayer Leverkusen,From Corner,...,Left Center Back,"[110.1, 41.6]",0.589561,"[30f5db44-0860-4a4f-b80b-26400493a9c9, bbe3246...","{'statsbomb_xg': 0.06755266, 'end_location': [...",3895302,904,904,30606,NaN
14,964b0272-4e02-472a-b09f-0f0d384c5f1c,2116,1,00:45:26.691,45,26,Shot,66,Werder Bremen,From Keeper,...,Right Wing Back,"[115.9, 40.1]",0.100281,[a9ca8093-75c6-452a-8742-f7a23f86ff47],"{'one_on_one': True, 'statsbomb_xg': 0.3757361...",3895302,176,176,8576,NaN
15,6db2523e-9343-461c-a8d6-b202470c1e0b,2573,2,00:05:35.695,50,35,Shot,76,Werder Bremen,Regular Play,...,Right Center Midfield,"[97.5, 40.8]",0.797523,"[5fc76f6e-ce21-48a2-bd03-476e03408507, 7398c7e...","{'statsbomb_xg': 0.048408102, 'end_location': ...",3895302,176,176,8826,True
16,df7d8278-f139-4102-9e6e-3c77d3d575c3,2972,2,00:13:10.827,58,10,Shot,94,Bayer Leverkusen,From Corner,...,Left Attacking Midfield,"[93.8, 34.8]",1.038535,"[66b446fc-0d12-4b3b-8f18-4b73430b08ff, 69fe98a...","{'statsbomb_xg': 0.02420186, 'end_location': [...",3895302,904,904,40724,True
17,96146263-06f4-4694-8e44-44658af8b8f5,3023,2,00:14:18.478,59,18,Shot,96,Bayer Leverkusen,Regular Play,...,Right Defensive Midfield,"[93.0, 39.1]",1.029131,[3d0a67d4-150d-4560-9de5-91212e93f6b6],"{'statsbomb_xg': 0.031472735, 'end_location': ...",3895302,904,904,3500,NaN
18,7b3398ab-6dae-42ec-8b11-0cd333d6b085,3137,2,00:19:10.632,64,10,Shot,99,Bayer Leverkusen,Regular Play,...,Left Attacking Midfield,"[106.3, 29.6]",0.198394,"[88eb77f1-6e10-4290-bbf3-a602b946c8ab, c66d8f6...","{'statsbomb_xg': 0.07621976, 'end_location': [...",3895302,904,904,40724,NaN
19,5085715b-09f6-403c-8b67-a546bcfed0ec,3284,2,00:22:25.400,67,25,Shot,106,Bayer Leverkusen,From Throw In,...,Left Attacking Midfield,"[93.5, 40.1]",0.897301,[e2ed3687-064d-48f0-86f1-da4a13ede49b],"{'statsbomb_xg': 0.042012483, 'end_location': ...",3895302,904,904,40724,NaN
20,ec3f4afc-df7d-4a53-98a2-508e21c040eb,3348,2,00:25:17.218,70,17,Shot,108,Bayer Leverkusen,From Goal Kick,...,Center Forward,"[112.5, 29.6]",0.427660,[092943a4-bcb9-4ca7-9229-1d4980f471dc],"{'statsbomb_xg': 0.109270036, 'end_location': ...",3895302,904,904,7044,NaN
21,0af7b077-170b-4ca3-a61f-4ecb4aba33d1,3438,2,00:26:31.458,71,31,Shot,110,Werder Bremen,From Throw In,...,Right Wing Back,"[108.0, 51.1]",0.282564,[7460888a-8f35-4308-ac01-4664c8660d5b],"{'statsbomb_xg': 0.17347074, 'end_location': [...",3895302,176,904,32712,NaN
22,856a63cb-2fbc-4a03-b3ab-c0b98f377391,3646,2,00:29:42.717,74,42,Shot,117,Werder Bremen,From Throw In,...,Left Wing Back,"[108.1, 27.2]",0.869065,[54e7e350-f46b-4b42-a68d-4e7e6a485e67],"{'statsbomb_xg': 0.047987003, 'end_location': ...",3895302,176,176,24179,NaN
23,db15dcc2-36bb-4a82-b5ef-c15e68638ce9,3649,2,00:29:45.835,74,45,Shot,117,Werder Bremen,From Throw In,...,Left Center Midfield,"[98.2, 42.1]",1.280355,[64aa80a8-fcec-4323-a96e-b34af2c85db2],"{'statsbomb_xg': 0.03447609, 'end_location': [...",3895302,176,176,8784,NaN
24,d6a308ca-0f8f-44d5-ad64-aa8870e489ce,3887,2,00:35:22.811,80,22,Shot,126,Bayer Leverkusen,Regular Play,...,Left Defensive Midfield,"[101.6, 43.3]",0.935539,[64ef1a44-903a-45ed-994f-1dcf663e83f6],"{'statsbomb_xg': 0.06844198, 'end_location': [...",3895302,904,904,28268,NaN
25,4a223f2d-3c3f-4655-b561-9c43a03b0f42,3984,2,00:37:29.786,82,29,Shot,131,Bayer Leverkusen,From Counter,...,Left Attacking Midfield,"[103.6, 35.0]",0.464015,[4a00ec6b-df99-4893-9504-e1670218ab90],"{'one_on_one': True, 'statsbomb_xg': 0.4383271...",3895302,904,904,40724,NaN
26,dcc0c591-7ebd-4e42-8206-04bfefa94f33,4220,2,00:44:25.079,89,25,Shot,143,Bayer Leverkusen,From Counter,...,Left Attacking Midfield,"[106.4, 48.8]",0.818232,[c079bf98-61b4-48b4-8b66-f3f0c1aa19f3],"{'statsbomb_xg': 0.28999847, 'end_location': [...",3895302,904,904,40724,NaN

In [5]:
sb.events(match_id=3895302, split=True, flatten_attrs=False).keys()

c:\Users\Alexander Lorenz\anaconda3\envs\aifc\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

dict_keys(['starting_xis', 'half_starts', 'passes', 'ball_receipts', 'carrys', 'pressures', 'miscontrols', 'dribbles', 'duels', 'interceptions', 'ball_recoverys', 'dispossesseds', 'blocks', 'foul_committeds', 'foul_wons', 'errors', 'shots', 'goal_keepers', 'injury_stoppages', 'referee_ball_drops', '50/50s', 'clearances', 'offsides', 'dribbled_pasts', 'player_offs', 'player_ons', 'half_ends', 'substitutions', 'bad_behaviours', 'tactical_shifts', 'shields'])

In [6]:
games = (matches["home_team"] == "Bayer Leverkusen") | (matches["away_team"] == "Bayer Leverkusen")
game_ids = matches[games]["match_id"]
game_ids = game_ids.to_list()

shot_attempts_locations = []

for id in game_ids:
    shots = sb.events(match_id=id, split=True, flatten_attrs=False)["shots"]
    mask = shots["player"] == "Florian Wirtz"
    wirtz_shots = shots[mask]
    locations = wirtz_shots["location"].to_list()
    
    if len(locations) != 0:
        shot_attempts_locations.append(locations)

In [7]:
import matplotlib.pyplot as plt
from mplsoccer import Pitch, VerticalPitch
import numpy as np

X = np.vstack(shot_attempts_locations)

pitch = Pitch(label=True, tick=True)
fig, ax = pitch.draw(figsize=(8, 4))

ax.scatter(X[:, 0], X[:, 1], c='lightblue', s=50, edgecolors='black', zorder=5)

# Display the plot
plt.show()

ValueError: need at least one array to concatenate

In [ ]:
import json
import os

# Bundesliga
competition_id = 9
season_id = 281

# open Euro 2024
with open(f'../data/matches/{competition_id}/{season_id}.json', 'r') as file:
    data = json.load(file)

# get match ids
match_ids = []
for n in range(len(data)):
    match_ids.append(data[n].get('match_id'))

# check if event data exists
for match_id in match_ids:
    if os.path.exists(f'../data/events/{match_id}.json'):
        pass
    else:
        print(f"File does not exist: {match_id}.json")

match_ids[0:2]

[3895302, 3895292]

In [ ]:
with open(f'../data/events/{3895302}.json', 'r') as file:
    data = json.load(file)

data[2]

{'id': '1f956a2b-ece0-475b-8802-e82ed922c307',
 'index': 3,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 18, 'name': 'Half Start'},
 'possession': 1,
 'possession_team': {'id': 904, 'name': 'Bayer Leverkusen'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 904, 'name': 'Bayer Leverkusen'},
 'duration': 0.0,
 'related_events': ['79b90fbb-2cfd-419b-90f4-f0e5980c47d3']}

In [ ]:
event_id = data[4]["id"]
halft_time = data[4]["period"]
timestamp = data[4]["timestamp"]
team = data[4]["team"]
player = data[4]["player"]
position = data[4]["position"]
location = data[4]["location"]
duration = data[4]["duration"]
data[4]["pass"]

{'recipient': {'id': 12299, 'name': 'Marvin Ducksch'},
 'length': 2.1540658,
 'angle': 2.7610862,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [59.0, 40.9],
 'body_part': {'id': 40, 'name': 'Right Foot'},
 'type': {'id': 65, 'name': 'Kick Off'}}

In [ ]:
shot_attempts_pos = []
goals_pos = []

for event in data:
    # shot attempts
    if event["type"].get("id") == 16 and event["player"].get("name") == "Florian Wirtz":
        shot_attempts_pos.append(event["location"])
    
shot_attempts_pos

[[93.8, 34.8], [106.3, 29.6], [93.5, 40.1], [103.6, 35.0], [106.4, 48.8]]